### ISSUE TITLE
Entities killed by player not logged

### ISSUE THREAD

**Issue by kangarko** [addstar/Prism-Bukkit#2]
Even if I have entity-kill enabled Prism won't show anything.
Tested on testing account with player permissions.

It only shows "spawner egg spawned X" and "kangarko2 used monster egg" (kangarko2 is a testing account without OP and all other actions are being normally tracked)

Config: http://pastebin.com/EJLsUTAP
Using your latest prism forked and compiled as of commit "Track/rollback banner patterns + properly track spawners and skulls".

Edit: I noticed that for example a Zombie killed by fire tick is logged as the entity-kill action, but not when killed by a player.

**Comment by addstar** [comment]
@kangarko, I just did some tests just to be sure, and it's working fine.
I think the problem is that you are searching for the wrong event (I didn't realise it at the time of reading your issue, until I did the testing myself):
* a:entity-kill = when an entity is killed by a non-player entity
* a:player-kill = when an entity is killed by a player
* a:kill = includes both of the above (players + non-players)-

---
```config
/prism lookup r:15 a:kill
Prism // Showing 5 results. Page 1 of 1
 -  [1] add5tar killed white sheep 4m ago (a:kill)
 -  [2] add5tar killed zombie 9m ago (a:kill)
 -  [3] add5tar killed chicken 9m ago (a:kill)
 -  [4] add5tar killed squid 9m ago (a:kill)
 -  [5] Wolf killed white sheep 9m ago (a:kill)

/prism lookup r:15 a:entity-kill
Prism // Showing 1 results. Page 1 of 1
 -  [1] Wolf killed white sheep 9m ago (a:kill)

/prism lookup r:15 a:player-kill
Prism // Showing 4 results. Page 1 of 1
 -  [1] add5tar killed white sheep 4m ago (a:kill)
 -  [2] add5tar killed zombie 9m ago (a:kill)
 -  [3] add5tar killed chicken 9m ago (a:kill)
 -  [4] add5tar killed squid 9m ago (a:kill)
```
---
For testing you should use /prism near or /prism lookup r:15 just to be sure you included everything. Then you can refine your search to include exactly what you need.

**Comment by kangarko** [comment]
Thanks for the answer.

I am using everything like you said, e.g. /prism near, also tried /prism lookup p:testUser a:kill but it didn't find anything.

It seems like some rare case, because everything else is, I thing, logged correctly. I will do more research, but I am unable to run Prism on a local server. What mysql db software are you using?

**Comment by kangarko** [comment]
Thank you very much! I did not realized that it was "player-kill" that triggered the logging ;) I though it was only for logging PvP. The issue is therefore fixed now.
